### ISSUE TITLE
Circular dependency in DI detected for ApplicationRef

### ISSUE THREAD

**Issue by JanMalch** [ngneat/hot-toast#70]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other...
</code></pre>

## Current behavior

When trying to inject the `HotToastService` in a custom `ErrorHandler` I get the following error:

```
Error: NG0200: Circular dependency in DI detected for ApplicationRef. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.js:216)
    at R3Injector.hydrate (core.js:11408)
    at R3Injector.get (core.js:11232)
    at injectInjectorOnly (core.js:4728)
    at ɵɵinject (core.js:4732)
    at Object.ViewService_Factory [as factory] (ngneat-overview.js:437)
    at R3Injector.hydrate (core.js:11412)
    at R3Injector.get (core.js:11232)
    at injectInjectorOnly (core.js:4728)
    at ɵɵinject (core.js:4732)
```

Other components can inject the service without any issues.

## Expected behavior

Should be able to inject the service in the custom error handler. 

## Minimal reproduction of the problem with instructions

Setup the library and the following service:

```ts
@Injectable()
export class AppErrorHandlerService implements ErrorHandler {
  constructor(private readonly toast: HotToastService) {}

  handleError(error: any): void {
    this.toast.error('Unexpected error.');
    console.error(error);
  }
}
```

Provide via `{ provide: ErrorHandler, useClass: AppErrorHandlerService }`.

The issue might've been introduced with Angular v12, as another project on v11 has this pattern working.

## Environment

<pre><code>"@angular/core": "~12.0.2",
"@ngneat/hot-toast": "^2.0.2",
"@ngneat/overview": "^1.0.0",
</code></pre>

**Comment by shhdharmen** [comment]
I think this will get resolved with #62. I am working in it.

**Comment by shhdharmen** [comment]
@JanMalch can you try to update hot-toast to v3? And see if the error is still coming...

**Comment by JanMalch** [comment]
Unfortunately it still doesn't work. I've created a demo repository: https://github.com/JanMalch/hot-toast-circular-app-ref

```
Error: NG0200: Circular dependency in DI detected for ApplicationRef. Find more at https://angular.io/errors/NG0200
    at throwCyclicDependencyError (core.js:216)
    at R3Injector.hydrate (core.js:11408)
    at R3Injector.get (core.js:11232)
    at injectInjectorOnly (core.js:4728)
    at Module.ɵɵinject (core.js:4732)
    at Object.ViewService_Factory [as factory] (ngneat-overview.js:261)
    at R3Injector.hydrate (core.js:11412)
    at R3Injector.get (core.js:11232)
    at injectInjectorOnly (core.js:4728)
    at ɵɵinject (core.js:4732)
```

**`ngneat-overview.js:261`**

```js
ViewService.ɵprov = i0.ɵɵdefineInjectable({ factory: function ViewService_Factory() { return new ViewService(i0.ɵɵinject(i0.ComponentFactoryResolver), i0.ɵɵinject(i0.INJECTOR), i0.ɵɵinject(i0.ApplicationRef)); }, token: ViewService, providedIn: "root" });
```

**Comment by shhdharmen** [comment]
You can get `HotToastService` from `Injector`:

```typescript
    import { ErrorHandler, Inject, Injectable, Injector } from '@angular/core';
    import { HotToastService } from '@ngneat/hot-toast';

    @Injectable({ providedIn: 'root' })
    export class AppErrorHandlerService implements ErrorHandler {
      constructor(@Inject(Injector) private readonly injector: Injector) {}

     /**
     * Need to get HotToastService from injector rather than constructor injection to avoid cyclic dependency error
     * @returns {} 
     */
      private get toast() {
        return this.injector.get(HotToastService);
      }

      handleError(error: any): void {
        this.toast.error(error.message);
        console.error(error);
      }
    }
```

**Comment by JanMalch** [comment]
That works, thanks.

**Comment by wellington1993** [comment]
> You can get `HotToastService` from `Injector`:
> 
> ```ts
>     import { ErrorHandler, Inject, Injectable, Injector } from '@angular/core';
>     import { HotToastService } from '@ngneat/hot-toast';
> 
>     @Injectable()
>     export class AppErrorHandlerService implements ErrorHandler {
>       constructor(@Inject(Injector) private readonly injector: Injector) {}
> 
>      /**
>      * Need to get HotToastService from injector rather than constructor injection to avoid cyclic dependency error
>      * @returns {} 
>      */
>       private get toast() {
>         return this.injector.get(HotToastService);
>       }
> 
>       handleError(error: any): void {
>         this.toast.error(error.message);
>         console.error(error);
>       }
>     }
> ```
> 
> Ref: [scttcper/ngx-toastr#327 (comment)](https://github.com/scttcper/ngx-toastr/issues/327#issuecomment-361304175)

Saved my day! Thanks!
